feat: Add project caching and id validation
WalletConnect/cerberus pull request #1
Opened 2022-10-26 13:58 UTC by xav

# Description

Add project data caching and validation, extracted from `relay`

## Due Diligence

* [x] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2022-10-27 06:14 UTC, heilhead commented
@xav As discussed on slack, let's get rid of metrics and redis stuff here. Instead move project & origin validation here. And copy the rest directly into consuming projects (`rpc-proxy`).

2022-10-27 06:22 UTC, heilhead requested changes

2022-10-27 06:22 UTC, heilhead commented on Cargo.toml
> +tokio = { version = "1", features = ["full"] }
Why do we need `tokio` here?

Also, `features = ["full"]` is bad practice, especially for libraries like this. The fewer features we enable, the faster compilation times will be. What we should do instead is set `default-features = false` and then only enable the required features (possibly feature-gating nested crates' features [like this](https://github.com/WalletConnect/wither/blob/master/wither/Cargo.toml#L36-L45)).

2022-10-27 06:22 UTC, heilhead commented on src/project/mod.rs
> +pub fn validate_project_access(
Let's make this a method on the `ProjectData` struct.

2022-10-28 16:19 UTC, xav commented on Cargo.toml
> +tokio = { version = "1", features = ["full"] }
cache and metrics are conditionals now (with their respective features)

2022-10-28 16:20 UTC, xav commented on src/project/mod.rs
> +pub fn validate_project_access(
done

2022-10-31 08:07 UTC, heilhead reviewed
Looking at what feature gating does to code, and how we pull in the dependencies (`rs-common`, `redis`, `opentelemetry` etc.), I still think we should just scrap all of this, and copy  the caching & metrics code directly into consuming project, leaving cerberus lean and clean.

`rs-common` on the other hand makes more sense to be able to reuse some of the abstractions that we have, though the question is still wether we have enough share-able abstractions to justify a separate crate. [This](https://github.com/WalletConnect/rs-common/blob/main/src/storage/redis/config.rs) though definitely needs to be removed, as it's relay-specific configuration and it has no place in that crate. And overall, `rs-common` needs some clean up.

2022-10-31 08:07 UTC, heilhead commented on src/registry/metrics/mod.rs
> +    #[cfg(feature = "cache")]
Looking at all of this it's unclear what values are available in cache-less version, and how they are recorded...

2022-10-31 10:14 UTC, xav commented on .github/workflows/ci.yaml
> +          toolchain: nightly
Because of the unstable features in `rustfmt.toml`, which was copied from relay.
`rust fmt` complains a lot with stable.

2022-10-31 10:37 UTC, xav commented on src/registry/cache/types.rs
> +                                                              // .tap_err(|err| warn!(?err, "error fetching data from project data cache"))?;
I'm not sure about them.
They are in the original and are an excellent idea, but we're missing all the tracing infrastructure here so that's an issue.
So that was my cop-out. I don't want to bring in more unrelated stuff, but I don't want to lose them either. 😄 
We can discuss your root comment about having caching and metrics in cerberus and decide from there what to do with them.

2022-10-31 14:13 UTC, xav commented on src/registry/cache/types.rs
> +        let data = self.cache.get(&cache_key).await.unwrap(); //?;
Done

2022-10-31 15:12 UTC, xav commented on src/registry/error.rs
> +    #[cfg(feature = "cache")]
These variants don't make sense if caching is not used, do we really still want them in?

2022-10-31 15:12 UTC, xav commented on src/registry/cache/types.rs
> +pub(crate) struct ProjectStorage {
Removed `types` and put everything into `mod` instead.

2022-10-31 16:11 UTC, heilhead commented on .github/workflows/ci.yaml
> +          toolchain: nightly
I think we should be building, checking and running tests against the latest stable version, while doing `cargo +nightly fmt` using nightly rustfmt. This way we can be sure that no nightly features slip into our code base and cause build issues down the line.

2022-10-31 16:16 UTC, heilhead commented on src/registry/cache/types.rs
> +                                                              // .tap_err(|err| warn!(?err, "error fetching data from project data cache"))?;
Yeah, tracing may be a bit too heavy to carry around for a bunch of primitive logs like these, but you can use [`log`](https://crates.io/crates/log) which will respect the logging output config of the consuming project.

2022-11-02 02:32 UTC, closed without merging